### ISSUE TITLE
Permit / login issue

### ISSUE THREAD

**Issue by rifqiramadhani** [soniibrol/absensi#1]
Maaf pak, apakah fungsi login memang tidak dicantumkan dalam program ini?

**Comment by soniibrol** [comment]
Program ini sudah termasuk login, fungsinya bisa dilihat di controller user.
[https://github.com/soniibrol/absensi/blob/master/application/controllers/user.php](url)

Semoga bermanfaat.

**Comment by rifqiramadhani** [comment]
Baik pak, tetapi yang terjadi seperti ini, ada di gambar attachment pak.
Terima kasih

On Jan 30, 2017 15:45, "Soni Ibrol" <notifications@github.com> wrote:

Program ini sudah termasuk login, fungsinya bisa dilihat di controller user.
https://github.com/soniibrol/absensi/blob/master/
application/controllers/user.php <http://url>

Semoga bermanfaat.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/soniibrol/absensi/issues/1#issuecomment-276006593>, or mute
the thread

**Comment by soniibrol** [comment]
Maaf mas, attachment nya dimana ya?

**Comment by rifqiramadhani** [comment]
Saya reupload pak, di imgur http://imgur.com/a/GwIvu

**Comment by soniibrol** [comment]
coba klik link nya, nanti akan redirect ke halaman login. saya belum redirect otomatis ke halaman login nya.

**Comment by rifqiramadhani** [comment]
Jika link saya klik, terjadi error 404 object not found. Seprti gambar ini
http://imgur.com/a/0HGzf
Maaf sebelumnya jika mengganggu

**Comment by soniibrol** [comment]
oh kalau itu .htaccess nya
coba tambahkan file .htaccess di root aplikasi nya

ini isinya:
RewriteEngine on
RewriteRule ^$ index.php [L]
RewriteCond $1 !^(index.php)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]

**Comment by rifqiramadhani** [comment]
Baik pak, terima kasih. Program sudah bisa dibuka dengan membuat .htaccess
ini, dan bisa masuk lewat login. Terima kasih banyak

**Comment by soniibrol** [comment]
Oke.
Semoga programnya membantu.
